name: BINARY_VERSION

on:
  create:
     tags:
       - '*'
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: macos-11

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Make build file for macOS
        env:
          GIT_COMMIT: ${{ github.sha }}
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          go mod tidy
          env GOOS=darwin go build -ldflags="-s -w -X 'main.BINARY_VERSION=${GITHUB_REF##*/}'" -o cf/lrc_macos .
      - name: Run
        run: ./cf/lrc_macos -v