name: Build and deploy

on:
  push:
    branches:
      - CI

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: Build
        run: |
          go build -o controlfloor .