name: Build and deploy

on:
  push:
    branches:
      - CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go version
          go get -u github.com/golang/dep/cmd/dep
          dep ensure
      - name: Build
        run: |
          go build -o controlfloor .